name: Build and Release
env:
  release_file: build/Release/bin/main.exe
  release_dir: build/Release/bin/
  release_zip: main.zip
on:
  # push:
  #   tags:
  #     - "*" # åªåŒ¹é… tag
  workflow_dispatch: # ä¹Ÿå¯æ‰‹åŠ¨è§¦å‘

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1ï¸âƒ£ æ£€å‡ºä»“åº“
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2ï¸âƒ£ è®¾ç½® MSVC å¼€å‘ç¯å¢ƒ
      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch:
            x64

            # ---------- Windows Qt Installation ----------
      - name: Install Qt (Windows)
        if: runner.os == 'Windows'
        uses: jurplel/install-qt-action@v4
        with:
          version: "5.12.12"
          target: "desktop"
          arch: "win64_msvc2017_64"
          install-deps: true
      # 3ï¸âƒ£ é…ç½® CMakeï¼ˆNinjaï¼‰
      - name: Configure CMake
        run: |
          $testenv = "hello test env"
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$env:QT_ROOT_DIR"

      - name: Linux Build with Ninja
        if: runner.os == 'Linux'
        run: |
          cmake --build build --config Release --parallel

      - name: Windows build with Ninja and deploy Qt
        if: runner.os == 'Windows'
        run: |
          Write-Host "Test Env Variable: $testenv"

          $qtPrefix = "$env:QT_ROOT_DIR"
          Write-Host "Qtå®‰è£…è·¯å¾„: $qtPrefix"

          # è¾“å‡ºä¸€çº§ç›®å½•ç»“æ„
          Write-Host "---- Qt ä¸€çº§ç›®å½•ç»“æ„ ----"
          Get-ChildItem -Path $qtPrefix | ForEach-Object { Write-Host $_.FullName }

          # è®¾ç½® PATH
          $env:PATH = "$qtPrefix\bin;$env:PATH"

          # è¾“å‡º PATH éªŒè¯
          Write-Host "PATH=$env:PATH"

          # ç¼–è¯‘
          cmake --build build --config Release --parallel

          # éƒ¨ç½² Qt ä¾èµ–
          windeployqt "${{ env.release_file }}"

           Write-Host "ğŸ“¦ å‹ç¼©ç›®å½•: ${{ env.release_dir }}"
          if (Test-Path "${{ env.release_zip }}") {
            Remove-Item "${{ env.release_zip }}" -Force
          }
          Compress-Archive -Path "${{ env.release_dir }}*" -DestinationPath "${{ env.release_zip }}" -Force
          Write-Host "âœ… æ‰“åŒ…å®Œæˆ: ${{ env.release_zip }}"


      # 5ï¸âƒ£ ä¸Šä¼ æ„å»ºäº§ç‰©åˆ° Actionsï¼ˆè°ƒè¯•æŸ¥çœ‹ï¼‰
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          name: build-artifacts
          path: "${{ env.release_zip }}"

      # 6ï¸âƒ£ ä¸Šä¼ æ„å»ºäº§ç‰©åˆ° GitHub Release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag' &&  runner.os == 'Windows'
        with:
          files: "${{ env.release_zip  }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
